[package]
name = "zebin"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
zebin-macros.workspace = true
memoffset = "0.9"
memmap2 = { version = "0.9", optional = true }
wide = { version = "1.3.0", default-features = false }

[features]
default = ["std"]
std = ["alloc"]
alloc = []
mmap = ["dep:memmap2", "std"]

[lints]
workspace = true
