[package]
name = "zebin"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
zebin-macros.workspace = true
memoffset = "0.9"
memmap2 = { version = "0.9", optional = true }
hashbrown = { version = "0.17", default-features = false, features = ["alloc"], optional = true }
ahash = { version = "0.8", default-features = false, optional = true }
wide = { version = "1.3.0", default-features = false }

[features]
default = ["std"]
no_std = ["dep:hashbrown", "dep:ahash"]
std = []
mmap = ["dep:memmap2", "std"]

[lints]
workspace = true
